stages:
  - copy

copy:
  stage: copy
  script: rsync -rult --delete-after --exclude=.git/ --exclude=.gitlab-ci.yml --password-file=/etc/rsyncd.scrt $CI_PROJECT_DIR/ rsync_ilya@192.168.101.13::wordpress
  rules:
    - if: $CI_COMMIT_TAG