---
- name: Gitlab | test
  ansible.builtin.debug:
    msg: System 

- name: Gitlab | install packages
  become: true
  become_method: sudo
  yum:
    name:
      - vim
      - vim-enhanced
      - mc
      - wget
      - docker
      - rsync
      - git
  async: 600
  poll: 30

- name: Gitlab | Enable service Docker, and not touch the state
  become: true
  become_method: sudo
  ansible.builtin.service:
    name: docker
    enabled: yes
    
- name: Gitlab | Start service Docker
  become: true
  become_method: sudo
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Gitlab | add /etc/rsyncd.scrt in /etc/rsyncd.scrt
  become: true
  become_method: sudo
  ansible.builtin.template:
    src: ./templates/rsyncd.scrt
    dest: /etc/rsyncd.scrt

- name: Gitlab |  chmod 640 /etc/rsyncd.scrt
  become: true
  become_method: sudo
  ansible.builtin.shell:
    cmd: chmod 640 /etc/rsyncd.scrt
  ignore_errors: true

- name: Gitlab | copy /etc/systemd/system/node_exporter.service
  become: true
  become_method: sudo
  ansible.builtin.template:
    src: ./templates/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Gitlab | Install, Enable and restart node_exporter
  become: true
  become_method: sudo
  ansible.builtin.shell: |
      wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
      tar zxvf node_exporter-*.linux-amd64.tar.gz
      cd node_exporter-*.linux-amd64
      cp node_exporter /usr/local/bin/
      useradd --no-create-home --shell /bin/false nodeusr
      chown -R nodeusr:nodeusr /usr/local/bin/node_exporter
      systemctl daemon-reload
      systemctl enable node_exporter
      systemctl start node_exporter

- name: Gitlab | Enable service Rsync, and not touch the state
  become: true
  become_method: sudo
  ansible.builtin.service:
    name: rsyncd
    enabled: yes
  ignore_errors: true

- name: Gitlab | Start service Rsync
  become: true
  become_method: sudo
  ansible.builtin.service:
    name: rsyncd
    state: restarted
  ignore_errors: true

- name: Gitlab | Add repos Gitlab
  become: true
  become_method: sudo
  ansible.builtin.shell:
    cmd: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash
  when: "'gitlab' in inventory_hostname"
  ignore_errors: True

- name: Gitlab | install Gitlab-CE
  become: true
  become_method: sudo
  yum:
    name:
      - gitlab-ce
  async: 900
  poll: 30
  when: "'gitlab' in inventory_hostname"
  ignore_errors: True

  
- name: Gitlab | change a str
  become: true
  become_method: sudo
  ansible.builtin.lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: '^external_url'
    insertbefore: BOF
    line: external_url 'http://gitlab.kor-iv.ru'
  when: "'gitlab' in inventory_hostname"

- name: Gitlab | gitlab-ctl reconfigure
  become: true
  become_method: sudo
  ansible.builtin.shell:
    cmd: gitlab-ctl reconfigure
  when: "'gitlab' in inventory_hostname"
  async: 900
  poll: 30
  ignore_errors: True

- name: Gitlab | Add repos for Runner
  become: true
  become_method: sudo
  ansible.builtin.shell:
    cmd: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.rpm.sh | sudo bash
  when: "'runner' in inventory_hostname"
  ignore_errors: True

- name: Gitlab | install Gitlab-Runner
  become: true
  become_method: sudo
  yum:
    name:
      - gitlab-runner
  when: "'runner' in inventory_hostname"

- name: Gitlab | Extract Runner Registration Token directly from Gitlab Rails console
  become: true
  become_method: sudo
  ansible.builtin.shell: 'gitlab-rails runner -e production "puts Gitlab::CurrentSettings.current_application_settings.runners_registration_token"'
  register: runners_registration_token
  when: "'gitlab' in inventory_hostname"

- name: Gitlab | print runners_registration_token
  ansible.builtin.debug:
    var: runners_registration_token

- name: Gitlab | set gitlab_runner_token
  become: true
  become_method: sudo
  set_fact:
    gitlab_runner_token: "{{ hostvars['gitlab'].runners_registration_token.stdout }}"
  when: "'runner' in inventory_hostname"


- name: Gitlab | register shell runner
  become: true
  become_method: sudo
  ansible.builtin.command: |
    gitlab-runner register \
    --non-interactive \
    --url "http://gitlab.kor-iv.ru/" \
    --registration-token "{{ gitlab_runner_token|quote }}" \
    --description "shell-runner" \
    --run-untagged="true" \
    --tag-list "shell,runner" \
    --locked="false" \
    --executor "shell"
  when: "'runner' in inventory_hostname"

- name: Gitlab | add /home/ilya/.gitlab-ci.yml
  become: true
  become_method: sudo
  ansible.builtin.template:
    src: ./templates/.gitlab-ci.yml
    dest: /home/ilya/.gitlab-ci.yml
  when: "'gitlab' in inventory_hostname"
  ignore_errors: True

- name: Gitlab | wget Wordpress
  become: true
  become_method: sudo
  ansible.builtin.shell:
    cmd: wget http://WordPress.org/latest.tar.gz

- name: Gitlab | unpack Wordpress
  become: true
  become_method: sudo
  ansible.builtin.shell:
    cmd: tar -xzvf latest.tar.gz

- name: Gitgab | add wp-config.php in /home/ilya/wordpress/wp-config.php
  become: true
  become_method: sudo
  ansible.builtin.template:
    src: ./templates/wp-config.php
    dest: /home/ilya/wordpress/wp-config.php

- name: Gitgab | add wp-config.php in /home/ilya/wordpress/.gitlab-ci.yml
  become: true
  become_method: sudo
  ansible.builtin.template:
    src: ./templates/.gitlab-ci.yml
    dest: /home/ilya/wordpress/.gitlab-ci.yml

- name: Gitlab |  chown :gitlab-runner /etc/rsyncd.scrt
  become: true
  become_method: sudo
  ansible.builtin.shell:
    cmd: chown :gitlab-runner /etc/rsyncd.scrt
  when: "'runner' in inventory_hostname"
  ignore_errors: true    

- name: Gitlab | Read file /etc/gitlab/initial_root_password
  become: true
  become_method: sudo
  ansible.builtin.shell: cat /etc/gitlab/initial_root_password | grep "Password:"
  register: initial_gitlab_root_password
  when: "'gitlab' in inventory_hostname"

- name: Gitlab | Show file content
  become: true
  become_method: sudo
  ansible.builtin.debug:
    var: initial_gitlab_root_password
  when: "'gitlab' in inventory_hostname"
